version: "3.8"

services:
  mysql-payment:
    image: mysql:8.0
    container_name: mysql-payment
    environment:

      MYSQL_DATABASE: payment_service
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - payment_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - payment_network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - payment_network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5

  payment-service:
    build:
      context: .
      dockerfile: payment_container/Dockerfile
    container_name: payment-service
    depends_on:
      mysql-payment:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - payment_network

networks:
  payment_network:
    driver: bridge
