spring:
  datasource:
    url: jdbc:mysql://mysql-payment:3306/payment_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  jpa:
    show-sql: false

  redis:
    host: redis

  kafka:
    bootstrap-servers: kafka:9092